format = """
$directory\
$git_branch\
$git_metrics\
$git_status\
$nodejs\
$python\
$nix_shell\
$shell\
$line_break\
$character"""

[directory]
style = 'fg:white'
format = '[$path]($style)'
truncation_length = 4
truncation_symbol = '...'
truncate_to_repo = false

[shell]
disabled = false
fish_indicator = 'fish'
bash_indicator = 'bash'
nu_indicator = 'nu'
format = ' [$indicator]($style)'


[character]
success_symbol = '[\$](fg:green)'
error_symbol = '[\$](fg:red)'


[git_status]
# $all_status に含まれるワークツリーとステージング領域の状態
conflicted = '[=](bold red)'
stashed = '[\$](purple)'
deleted = '[✘](red)'
renamed = '[»](cyan)'
modified = '[!](yellow)'
staged = '[+](green)'
untracked = '[?](bright-black)'

# $ahead_behind はリモートとの差に応じて、このいずれか一つに展開される
ahead = '[⇡](green)'
behind = '[⇣](red)'
diverged = '[⇕](yellow)'

# 状態があるときだけ、白い角括弧の中に色分けした記号を表示する
format = '([\[](white)$all_status$ahead_behind[\]](white))'


[git_branch]
style = 'fg:#888888'
symbol = ''
format = ' [$symbol $branch]($style)'


[git_metrics]
disabled = false
added_style = 'bold fg:green'
deleted_style = 'bold fg:red'
format = '\([+$added]($added_style)/[-$deleted]($deleted_style)\)'
only_nonzero_diffs = true


[package]
disabled = true


[nodejs]
style = 'fg:#8cc84b'
format = ' [$symbol $version]($style)'
symbol = ''


[python]
detect_extensions = ['py', 'ipynb']
style = 'fg:#FFD343 bg:#3776AB'
format = ' [ $symbol( $version)( \($virtualenv\)) ]($style)'

[nix_shell]
symbol = '❄️'
pure_msg = '[pure](fg:green)'
impure_msg = '[impure](fg:yellow)'
style = ''
format = ' [$symbol $state( \($name\))]($style)'

[cmd_duration]
disabled = true
